---
- name: Setup SFS mount directory
  hosts: all
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{mount_url}}'
          mountpoint: '{{mount_point}}'
      when: '{{auto_mount|default("true")|bool}}'
    - role: autofs
    - slurm-worker

- name: Setup SFS mount directory
  hosts: slurm_submit:slurm_client
  vars:
    - sfs_mountpoint: '{{mount_point}}'
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{mount_url}}'
          mountpoint: '{{mount_point}}'
      when: '{{auto_mount|default("true")|bool}}'
    - role: autofs
    - slurm-client



